# Generated by Django 6.1 on 2026-09-19 22:09
# Hora Local Chilena: 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('tipo', models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('TALLER', 'Taller Mecánico'), ('SUPERVISOR', 'Supervisor')], max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_vehiculo', models.CharField(max_length=10)),
                ('fecha_evento', models.DateField()),
                ('tipo_antecedente', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='antecedentes/')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('es_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regla', models.CharField(max_length=100)),
                ('limite_kilometros_mantencion', models.PositiveIntegerField()),
                ('dias_maximo_revision', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=150)),
                ('entidad_afectada', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consulta', models.CharField(max_length=100)),
                ('criterios_busqueda', models.JSONField(help_text='Filtros guardados en formato JSON')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_flota', models.CharField(max_length=50, unique=True)),
                ('nombre_area', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones', to='vehiculos.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_vehiculo', models.CharField(max_length=10)),
                ('tipo_operacion', models.CharField(choices=[('USO_DIARIO', 'Uso Diario'), ('MANTENCION', 'Mantención Preventiva'), ('REPARACION', 'Reparación Correctiva')], max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='vehiculos.actor')),
                ('gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='vehiculos.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Excepcionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('nivel_prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='vehiculos.operacion')),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.PositiveIntegerField()),
                ('nivel_combustible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_registrados', to='vehiculos.operacion')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('TALLER', 'Taller'), ('ADMIN', 'Administrador')], max_length=50)),
                ('nivel_acceso', models.IntegerField(default=1)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actores', to='vehiculos.perfil'),
        ),
        migrations.CreateModel(
            name='Privada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido_sensible', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('perfil_autorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros_usados', models.TextField(blank=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('porcentaje_variacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interpretacion', models.TextField()),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tendencias', to='vehiculos.indicador')),
            ],
        ),
    ]
